AllCops:
  UseCache: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5
  # Include:
  Exclude:
    - 'bin/*'
    - 'lib/tasks/**/*'
    - 'Gemfile'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - '**/Rakefile'
    - '**/config.ru'
