inherit_gem:
  rubocop-rails:
    - config/rails.yml

# ========================
# = Global configuration =
# ========================

Rails:
  Enabled: true

AllCops:
  UseCache: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5
  # Include:
  Exclude:
    - 'bin/*'
    - 'lib/tasks/**/*'
    - 'Gemfile'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - '**/Rakefile'
    - '**/config.ru'

# =============
# = Lint cops =
# =============
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

# ==============
# = Style cops =
# ==============
Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

# ================
# = Metrics cops =
# ================
Metrics/LineLength:
  Max: 90
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# ===============
# = Layout cops =
# ===============

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/*'

Layout/IndentationWidth:
  Enabled: false
