Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/EmptyMethod:
  Enabled: false
